project:
  type: website
  render:
    - "*.qmd"
    - "!usc-psyc573-notes/"
  resources:
    - "docs/"

website:
  title: "PSYC 573 Bayesian Data Analysis (2024 Fall)"
  open-graph: true
  site-url: https://marklhc.quarto.pub/psyc573-2024fall/
  repo-url: https://github.com/marklhc/20243-psyc573-usc
  google-analytics: "UA-225295148"
  page-footer:
    left: "Copyright 2024, Hok Chio (Mark) Lai"
    right: |
      This website was built with <a href="https://quarto.org/">Quarto</a>.
  navbar:
    right:
      - href: index.qmd
        text: Home
      - modules.qmd
      - href: docs/index.html
        text: Notes
      - exercises/index.qmd
      - href: syllabus/index.qmd
        text: Syllabus
      - resources.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



