---
title: "Modules"
format: html
---

::: {.panel-tabset}

# Week 1

## Week Learning Objectives

By the end of this module, you will be able to 

- Navigate the course website and Blackboard site
- Identify the Slack channels relevant for the course
- Describe the historical origin of Bayesian statistics
- Identify components in research papers involving Bayesian analyses
- Render a simple Quarto (.qmd) file

## Task List

1. Review the [syllabus](/syllabus/index.qmd)
2. Review the resources (slides and [note][5])
3. Install/Update R and RStudio on your computer
4. Attend the Tuesday and Thursday class meetings
5. Complete the assigned readings
    * [McElreath ch. 1][2]
    * Supplemental (i.e., optional) reading: [Gigerenzer (2004)][1]
    * [Markdown Basics][4]
6. Introduce yourself on the #introduction Slack channel (as part of HW 1)
7. Complete Homework 1 (see instruction on Brightspace)

[1]: https://pure.mpg.de/rest/items/item_2101336/component/file_2101335/content
[2]: https://xcelab.net/rmpubs/sr2/statisticalrethinking2_chapters1and2.pdf
[4]: https://quarto.org/docs/authoring/markdown-basics.html
[5]: docs/01-intro.html

## Slides

<div>

```{=html}
<iframe class="slide-deck" src="slides/intro.html" width="525" height="350"></iframe>
```

</div>

[Link to HTML slides](/slides/intro.qmd){target="_blank"}

# Week 2

## Week Learning Objectives

By the end of this module, you will be able to 

- Describe the **subjectivist** interpretation of probability, and contrast it with the **frequentist** interpretation
- Compute probability density using **simulations**
- Compute **joint, marginal, and conditional probabilities** with two variables
- Apply Bayes' rule to obtain **posterior** from prior and data
- Explain what **data-order invariance** and **exchangeability** are
- Use **grid approximation** to obtain the posterior for a **Bernoulli** model

## Task List

1. Review the resources (slides and [notes][9])
2. Attend the Tuesday and Thursday class meetings
3. Complete the assigned readings
    * [McElreath ch. 2][2], 3
    * [James ch. 1][3]
4. Complete Homework 2 (due in two weeks; see instruction on Brightspace)

[2]: https://xcelab.net/rmpubs/sr2/statisticalrethinking2_chapters1and2.pdf
[3]: https://jamesstone.sites.sheffield.ac.uk/books/bayes-rule/an-introduction-to-bayes-rule-chapter-1
[9]: docs/02-probability.html

## Slides

<div>

```{=html}
<iframe class="slide-deck" src="slides/probability_and_bayes_theorem.html" width="525" height="350"></iframe>
```

</div>

[Link to HTML slides](/slides/probability_and_bayes_theorem.qmd){target="_blank"}

# Week 3

## Week Learning Objectives

By the end of this module, you will be able to 

- Apply **Bayesian workflow** to analyze real data with a **Bernoulli** model
- Explain the idea of a **conjugate prior**
- Summarize the posterior distribution using **simulations**
- Apply Bayesian **terminology** in summarizing the posterior
- Use R to perform **prior** and **posterior predictive checks**

## Task List

1. Review the resources (slides and [notes][11])
2. Attend the Tuesday and Thursday class meetings
3. Complete the assigned readings
    * [Johnson ch. 3][6]
    * [Getting started with CmdStanR][10]
4. Complete Homework 2 (see instruction on Brightspace)

[6]: https://www.bayesrulesbook.com/chapter-3
[10]: https://mc-stan.org/cmdstanr/articles/cmdstanr.html
[11]: docs/04-beta-bernoulli-model.html

## Slides

<div>

```{=html}
<iframe class="slide-deck" src="slides/one_parameter_models.html" width="525" height="350"></iframe>
```

</div>

[Link to HTML slides](/slides/one_parameter_models.qmd){target="_blank"}

:::

P.S.: If'd like to print the slides to PDF, follow <https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf>