{
  "hash": "7b4fcb8cc1113f2dcc91e203fdc44043",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Models\"\ndate-modified: last-modified\nformat: metropolis-revealjs\n---\n\n\n\n\n\n\n::: {.content-hidden unless-profile=\"class\"}\n\n- HW 2\n    * Law of total probability\n    * Posterior mean\n- One-parameter model\n    * Bernoulli\n    * Binomial\n    * Poisson\n- Stan, Exercise 3\n- Hierarchical models\n- HW 3\n- Exercise 4\n\n:::\n\n# Statistical Model\n\nA set of assumptions that form a simplified representation of how the data are generated\n\n## Regression\n\n![](https://upload.wikimedia.org/wikipedia/commons/6/62/Galton-height-regress.png){width=\"400\" fig-align=\"center\"}\n\n::: aside\nMadprime, CC0, via Wikimedia Commons\n:::\n\n## Regression\n\nA *systematic* and a *random* components\n\n\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-2-1.png){width=384}\n:::\n\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-2-2.png){width=384}\n:::\n:::\n\n\n\n\n## Regression for Prediction\n\nOne outcome $Y$, one or more predictors $X_1$, $X_2$, $\\ldots$\n\n. . .\n\nE.g.,\n\n- What will a student's college GPA be given an SAT score of $x$?\n- How long will a person live if the person adopts diet $x$?\n- What will the earth's global temperature be if the carbon emission level is $x$?\n\n## Keep These in Mind\n\n1. Likelihood function is defined for the outcome $Y$\n\n2. Prediction is probabilistic (i.e., uncertain) and contains error\n\n## Linear Regression\n\nMany relations can be approximated as linear\n\nBut many relations cannot be approximated as linear\n\n## Example: \"Bread and Peace\" Model\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n## Linear Regression Model\n\nModel:\n\n$$\n\\begin{aligned}\n  \\text{vote}_i & \\sim N(\\mu_i, \\sigma) \\\\\n  \\mu_i & = \\beta_0 + \\beta_1 \\text{growth}_i\n\\end{aligned}\n$$\n\n$\\sigma$: SD (margin) of prediction error\n\nPrior:\n\n$$\n\\begin{aligned}\n  \\beta_0 & \\sim N(45, 10)  \\\\\n  \\beta_1 & \\sim N(0, 10)  \\\\\n  \\sigma & \\sim t^+_4(0, 5)\n\\end{aligned}\n$$\n\n## Stan Code\n\n\n\n\n::: {.cell output.var='linear_reg'}\n\n```{.stan .cell-code}\ndata {\n  int<lower=0> N;  // number of observations\n  vector[N] y;  // outcome;\n  vector[N] x;  // predictor;\n  int<lower=0,upper=1> prior_only;  // whether to sample prior only\n}\nparameters {\n  real beta0;  // regression intercept\n  real beta1;  // regression coefficient\n  real<lower=0> sigma;  // SD of prediction error\n}\nmodel {\n  // model\n  if (!prior_only) {\n    y ~ normal(beta0 + beta1 * x, sigma);\n  }\n  // prior\n  beta0 ~ normal(45, 10);\n  beta1 ~ normal(0, 10);\n  sigma ~ student_t(4, 0, 5);\n}\ngenerated quantities {\n  // Prior/posterior predictive\n  array[N] real ytilde = normal_rng(beta0 + beta1 * x, sigma);\n}\n```\n:::\n\n\n\n\n\n\n## Meaning of Coefficients\n\nWhen growth = 0, $\\text{vote} \\sim N(\\beta_0, \\sigma)$\n\nWhen growth = 1, $\\text{vote} \\sim N(\\beta_0 + \\beta_1, \\sigma)$\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\n## Posterior Predictive Check\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-8-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\nThe model fits a majority of the data, but not everyone. The biggest discrepancy is 1952.\n\n## Posterior Distributions\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-9-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n\n\n## Prediction\n\n\n\n\n\n\n\n\n\nPredicted vote share when growth = 2: $\\tilde y \\mid y \\sim N(\\beta_0 + \\beta_1 \\times 2, \\sigma)$\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n\n\nProbability of incumbent's vote share > 50% = 0.72\n\n## Regression Diagnostics\n\n- **L**inearity\n- **I**ndependent observations\n    - Exchangeability in Bayesian (conditional on the predictors)\n- **N**ormality\n- **E**qual variance of errors\n    - Same $\\sigma$ for all observations\n- Correct **S**pecification of the model\n\n---\n\n::: {.content-hidden unless-profile=\"class\"}\n\n## Thought Exercise\n\nHow are the assumptions coded in the model?\n\n$$\n\\begin{aligned}\n  \\text{vote}_i & \\sim N(\\mu_i, \\sigma) \\\\\n  \\mu_i & = \\beta_0 + \\beta_1 \\text{growth}_i\n\\end{aligned}\n$$\n\n:::\n\n## Linearity (functional form)\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-12-1.png){width=100%}\n:::\n:::\n\n\n\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(m_lin, type = \"intervals\", x = \"x\") +\n    geom_smooth(se = FALSE, col = \"blue\") +\n    geom_smooth(aes(x = x, y = y), se = FALSE,\n                col = \"red\", linetype = \"dashed\")\n```\n\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-14-1.png){width=100%}\n:::\n:::\n\n\n\n\n:::\n\n::::\n\n## Residual Plots\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-15-1.png){width=100%}\n:::\n:::\n\n\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(m_lin_norm,\n         type = \"error_scatter_avg_vs_x\",\n         x = \"x\")\n```\n\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-17-1.png){width=100%}\n:::\n:::\n\n\n\n\n:::\n\n::::\n\n# Multiple Predictors\n\nData from the 2009 American Community Survey (ACS)\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-19-1.png){width=576}\n:::\n:::\n\n\n\n\n## Additive Model\n\n$$\n\\begin{aligned}\n  D_i & \\sim N(\\mu_i, \\sigma)  \\\\\n  \\mu_i & = \\beta_0 + \\beta_1 S_i + \\beta_2 A_i \\\\\n  \\beta_0 & \\sim N(0, 10) \\\\\n  \\beta_1 & \\sim N(0, 10) \\\\\n  \\beta_2 & \\sim N(0, 1)  \\\\\n  \\sigma & \\sim t^+_4(0, 3)\n\\end{aligned}\n$$\n\n- $\\beta_1$: Expected difference in divorce rate between southern and non-southern states **with the same median age of marriage**.\n- $\\beta_2$: Expected difference in divorce rate for one unit difference in median age of marriage, **when both states are southern (or non-southern)**.\n\n## The `brms` R package\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(brms)\noptions(brms.backend = \"cmdstanr\")  # use cmdstanr instead of rstan\nget_prior(Divorce ~ MedianAgeMarriage + South,\n          data = waffle_divorce)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                prior     class              coef group resp dpar nlpar lb ub\n               (flat)         b                                              \n               (flat)         b MedianAgeMarriage                            \n               (flat)         b        Southsouth                            \n student_t(3, 1, 2.5) Intercept                                              \n student_t(3, 0, 2.5)     sigma                                          0   \n       source\n      default\n (vectorized)\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\n\n\n::: {.callout-caution}\n\n## Beware of the default priors\n\nPlease note that the default priors could change in future versions of the `brms` package. It has changed in previous releases.\n:::\n\n---\n\n\n\n\n::: {.cell output-location='slide'}\n\n```{.r .cell-code}\nm_additive <- brm(\n    Divorce ~ South + MedianAgeMarriage,       # <1>\n    data = waffle_divorce,\n    prior = prior(normal(0, 2), class = \"b\") + # <2> \n        prior(normal(0, 10), class = \"b\", coef = \"Southsouth\") +\n        prior(normal(0, 10), class = \"Intercept\") +\n        prior(student_t(4, 0, 3), class = \"sigma\"),\n    seed = 941,                                # <3>\n    file = \"m_additive\"                        # <4>\n)\nsummary(m_additive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: Divorce ~ South + MedianAgeMarriage \n   Data: waffle_divorce (Number of observations: 50) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nPopulation-Level Effects: \n                  Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept             3.01      0.45     2.12     3.89 1.00     3949     2957\nSouthsouth            0.08      0.05    -0.01     0.18 1.00     3943     2798\nMedianAgeMarriage    -0.79      0.17    -1.13    -0.45 1.00     3947     2918\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.15      0.02     0.12     0.18 1.00     3284     2523\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n1. Same formula syntax as in `lm()`.\n2. Prior distributions (`class = b`{.r} for $\\beta$ coefficients, `sigma` for the $\\sigma$ parameter)\n3. For reproducibility\n4. Save results to `m_additive.rds`\n\n---\n\nSlopes are parallel\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\n\n\n## Interactions\n\n$$\n\\begin{aligned}\n  D_i & \\sim N(\\mu_i, \\sigma)  \\\\\n  \\mu_i & = \\beta_0 + \\beta_1 S_i + \\beta_2 A_i + \\beta_3 S_i \\times A_i \\\\\n  \\beta_0, \\beta_1 & \\sim N(0, 10) \\\\\n  \\beta_2 & \\sim N(0, 1) \\\\\n  \\beta_3 & \\sim N(0, 2) \\\\\n  \\sigma & \\sim t^+_4(0, 3)\n\\end{aligned}\n$$\n\n- $\\beta_1$: Difference in intercept between southern and non-southern states.\n- $\\beta_3$: Difference in the coefficient for A &rarr; D between southern and non-southern states\n\n---\n\n::: {.callout-caution}\n\n## $\\beta_1$ and $\\beta_2$ Are Not Main Effects\n\nWhen an interaction term is included, the coefficient of $A$ is the **conditional effect when $S$ = 0.**\n\n:::\n\n## Reporting I\n\n> We fit a Bayesian linear model using the *brms* R package to examine the interaction effects between state-level median age of marriage and location of the state (southern vs. non-southern). We use weakly informative priors for all model parameters, as shown below: [insert the model equations]\n\n## Reporting II\n\n> The posterior distributions are obtained using Markov Chain Monte Carlo (MCMC) sampling, with 4 chains and 2,000 iterations for each chain (the first 1,000 discarded as warm-ups). Convergence of MCMC chains were determined by examining trace plots of the posterior samples and the $\\hat R$ statistics (< 1.01 for all model parameters; Vehtari et al., 2021), and the effective sample sizes are > 400 to ensure accurate approximation of the posterior distributions.\n\n---\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: Divorce ~ South * MedianAgeMarriage \n   Data: waffle_divorce (Number of observations: 50) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nPopulation-Level Effects: \n                             Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nIntercept                        2.78      0.46     1.87     3.68 1.00     4716\nSouthsouth                       3.20      1.60     0.19     6.30 1.00     2863\nMedianAgeMarriage               -0.70      0.18    -1.05    -0.35 1.00     4714\nSouthsouth:MedianAgeMarriage    -1.22      0.62    -2.42    -0.03 1.00     2876\n                             Tail_ESS\nIntercept                        4042\nSouthsouth                       3608\nMedianAgeMarriage                4085\nSouthsouth:MedianAgeMarriage     3584\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.14      0.02     0.12     0.18 1.00     4244     4998\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## Simple Slopes/Conditional Effects\n\n- Slope when South = 0: $\\beta_1$\n- Slope when South = 1: $\\beta_1 + \\beta_3$\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|variable   |  mean| median|   sd|  mad|    q5|   q95| rhat| ess_bulk| ess_tail|\n|:----------|-----:|------:|----:|----:|-----:|-----:|----:|--------:|--------:|\n|b_nonsouth | -0.70|  -0.71| 0.18| 0.18| -1.00| -0.41|    1|     4714|     4085|\n|b_south    | -1.92|  -1.91| 0.60| 0.60| -2.91| -0.93|    1|     3168|     3659|\n\n\n:::\n:::\n\n\n\n\n---\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Model-implied simple slopes based on the interaction model (posterior median and 95% symmetric credible band).](linear_models_files/figure-revealjs/fig-cond-eff-inter-1.png){#fig-cond-eff-inter width=960}\n:::\n:::\n\n\n\n\n---\n\n::: {.content-hidden unless-profile=\"class\"}\n\n## Thought Exercise\n\nWhere does the previous graph shows\n\n- $\\hat \\beta_0$ = 2.78\n- $\\hat \\beta_1$ = 3.20\n- $\\hat \\beta_2$ = -0.70\n- $\\hat \\beta_3$ = -1.22\n\n:::\n\n## Posterior Predictive Checks\n\n\n\n\n::: {.cell layout-nrow=\"2\"}\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-27-1.png){width=100%}\n:::\n\n::: {.cell-output-display}\n![](linear_models_files/figure-revealjs/unnamed-chunk-27-2.png){width=100%}\n:::\n:::\n\n\n\n\n## Reporting III\n\n\n\n\n\n\n\n\n\n> As shown in @fig-cond-eff-inter, median age of marriage negatively predicts divorce rate in both southern and non-southern states. For non-southern states, a 10-year difference in median age of marriage corresponds to a difference of -0.7 per 10 adults, 95% CI [-1.05, -0.35] in divorce rate. There is evidence for a nonzero interaction effect such that the negative association between median age of marriage and divorce rate in southern states is stronger than in non-southern states, $\\beta_3$ = -1.22, 95% CI [-2.42, -0.03].\n\n## Centering\n\nIntercept ($\\beta_0$): Predicted $y$ when all predictors are 0\n\n- i.e., non-southern states with median marriage age of 0.\n\n. . .\n\nTo make $\\beta_0$ more meaningful, center the predictors at a more meaningful value.\n\n---\n\nThe Intercept below shows the predicted divorce rate with a median age of marriage of 25. $\\beta_1$ represents the difference between southern and non-southern states **conditional** on median marriage age of 25.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: Divorce ~ South * I(MedianAgeMarriage - 2.5) \n   Data: waffle_divorce (Number of observations: 50) \n  Draws: 4 chains, each with iter = 4000; warmup = 2000; thin = 1;\n         total post-warmup draws = 8000\n\nPopulation-Level Effects: \n                                  Estimate Est.Error l-95% CI u-95% CI Rhat\nIntercept                             1.02      0.03     0.95     1.08 1.00\nSouthsouth                            0.16      0.06     0.04     0.28 1.00\nIMedianAgeMarriageM2.5               -0.70      0.18    -1.06    -0.35 1.00\nSouthsouth:IMedianAgeMarriageM2.5    -1.24      0.61    -2.42    -0.06 1.00\n                                  Bulk_ESS Tail_ESS\nIntercept                             7332     5420\nSouthsouth                            5730     5778\nIMedianAgeMarriageM2.5                7481     5345\nSouthsouth:IMedianAgeMarriageM2.5     6276     6331\n\nFamily Specific Parameters: \n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.14      0.02     0.12     0.18 1.00     7285     5539\n\nDraws were sampled using sample(hmc). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::",
    "supporting": [
      "linear_models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}